### ISSUE TITLE
Password send in plain text

### ISSUE THREAD

**Issue by Zephyrusg** [gboudreau/sabconnectplusplus#147]
is it possible to secure the password when send over the internet.
My netwerk analist saw my password i was sending over the air.
He warned me about this. 

http://xx.xx.xx:xxxx/sabnzbd/api?apikey=xxx&ma_username=admin&ma_password=xxxxxxxx&output=json&mode=queue&limit=5

**Comment by ppslim** [comment]
This will be a function of your sabnzbd installation, not the Chrome extension.

The immediate method to secure this whilst maintaining direct access would be using SSL certificates. These apply to configuration sabnzbd and then updating your extension config to point to https rather than http.

Removing that as an option, you need to remove external access and provide some form of indirect / tunneled access. Such alternatives include SSH tunnelling, thought not very elegant. Next would be a VPN, which I can recommend OpenVPN for a simple setup.

Other than the updates to the profile in the extension to account for these changes, all other assistance falls outside the scope we could assist with.

**Comment by pdf** [comment]
@ppslim this is definitely a problem with the extension - GET parameters should never be used to transmit passwords as they're recorded in HTTP server logs.

**Comment by ppslim** [comment]
Correct, this is indeed going against best practice in terms of security.

This extension and Sab allows use of the API, not just user/password. This extension will only include `ma_username` if the connection profile contains a username, likewise it will only have `ma_password` if the profile contains a password, and `apikey` if the profile has a API key.

As such, you can define if the request includes the user/password in the parameters, by omission of one or more of them in the connection profile. aka, correctly have a API key in the connection profile, but omit the username/password from the profile.

Should this fail to work, this is because Sab itself mandates that these credentials are supplied for one or more request types.

I will admit, it's not super clear why it needed the user/password in the request to begin with, as it was 14 years ago, so the intent is unknown. But it does list the change as making it work with the API key removed. A later change (13 years ago) included the option to omit these parameters from the request, based on their presence in the profile settings.

**Comment by pdf** [comment]
Yeah, I deleted the user/pass params from my profile. I suspect these params are probably safe to remote entirely.

Honestly, exposing the API key so almost as bad exposing the user/pass, though unfortunately SAB does this for its own UI requests (possibly worth filing there too).

I did a quick test by deleting the explicit user/pass params from those requests (they're in the body anyway), and setting all requests to use POST instead of GET and everything _seemed_ to work.
