### ISSUE TITLE
Extension seems to cause some sites to slowly scroll constantly

### ISSUE THREAD

**Issue by DaveHenning** [gboudreau/sabconnectplusplus#154]
I have noticed that specifically http://pitchfork.com/ & https://www.instagram.com/ will continously scroll down the page without any interaction. I'm not sure if it's only those two pages, but that's where I've definitely seen it happen. 

It only happens when NOT scrolled all the way to the top. In other words, if at the top of the page, there is no issue. But if you scroll any distance down, it starts auto scrolling.

I found it was the sabconnectplus extension by disabling all extensions one at a time until the issue stopped. 

Now, I'm no developer, but after digging around in Chrome's Inspect Tool, I've found that disabling margin:0px on the body seems to stop it. On both sites. Hopefully that is of some use.

Love the extension.

**Comment by migalicious** [comment]
Googled around to find a solution and it led me here after disabling my extensions one by one.  It's happening to me with https://sneakernews.com/ articles.

**Comment by eappell** [comment]
Same here - it happens on all Google documentation sites that I've found: 
https://angular.io/guide/, https://firebase.google.com/docs, etc.

Since this has been reported for a few years, doesn't look like anyone is ever going to fix this, so I guess the only workaround is to just disable it when viewing one of those sites.  In my tests, it doesn't require a browser restart, just disable the extension and refresh the page and it stops auto-scrolling.
